/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uespi.trabcons;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.event.*;

/**
 * Janela de visualização e manipulação dos dados de Aluno (Tabela, Pesquisa, Exclusão).
 * Ela opera sobre uma única instância de 'listaAlunos'.
 */
public class TrabConsData extends javax.swing.JFrame {

    // Referência obrigatória ao gerenciador de dados. É 'final' porque não pode mudar.
    private final listaAlunos gerenciaAlunos;

    // Construtor: RECEBE a instância do gerenciador de dados.
    public TrabConsData(listaAlunos gerenciaAlunos) {
        // Atribui a instância para que esta janela possa usá-la.
        this.gerenciaAlunos = gerenciaAlunos;

        initComponents();
        // Configura o texto de dica no campo de matrícula.
        SwingUtils.configurarPlaceholder(matFieldData, "Ex: 12345678");

        // Define o comportamento de fechamento: Apenas fecha esta janela (DISPOSE), não o programa inteiro.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Adiciona um listener para a janela.
        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            // Quando a janela é fechada, ela informa ao gerenciador que não presiza mais ser notificada.
            gerenciaAlunos.unregisterView();
        }
    });
        
        // Adiciona um listener ao JList (o filtro).
        listaFiltro.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Executa a atualização da tabela apenas quando o usuário solta o mouse.
                if (!e.getValueIsAdjusting()) {
                    atualizarTabela(); // Recarrega a tabela com a nova ordem.
                }
            }
        });

        // Exibe o número total de alunos no campo de texto.
        displayQnt.setText(this.gerenciaAlunos.getTamanho());

        // Carregamento inicial dos dados na tabela.
        atualizarTabela();
        // Registra esta janela no gerenciador para receber atualizações futuras.
        this.gerenciaAlunos.registerView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFiltro = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        matFieldData = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayQnt = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Matricula", "Data de Nacimento", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabela.setName("MatData"); // NOI18N
        tabela.setShowGrid(true);
        jScrollPane3.setViewportView(tabela);

        listaFiltro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mais Novo", "Mais Velho" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaFiltro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listaFiltro.setToolTipText("Lembre-se de clicar na opção!");
        listaFiltro.setVerifyInputWhenFocusTarget(false);
        listaFiltro.setVisibleRowCount(1);
        jScrollPane1.setViewportView(listaFiltro);

        jLabel17.setText("Filtro:");

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        matFieldData.setColumns(8);
        matFieldData.setText("Ex: 12345678");
        matFieldData.setToolTipText("Insira a matricula para pesquisar.");
        matFieldData.setInheritsPopupMenu(true);
        matFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matFieldDataActionPerformed(evt);
            }
        });

        jLabel16.setText("Matricula:");

        jScrollPane2.setViewportView(displayQnt);

        jLabel1.setText("Total de Alunos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(matFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(pesquisar)
                            .addComponent(excluir)
                            .addComponent(jLabel17)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Alunos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matFieldDataActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
          // 1. Pega o texto do campo de matrícula
        String matricula = matFieldData.getText();
        String placeholder = "Ex: 12345678";

        // 2. Valida se o campo não está vazio ou com o placeholder
        if (matricula.isEmpty() || matricula.equals(placeholder)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, digite uma matrícula para pesquisar.",
                "Campo Vazio",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Chama o método de busca que criamos no 'gerenciaAlunos'
        Aluno alunoEncontrado = this.gerenciaAlunos.buscarPorMatricula(matricula);

        // 4. Verifica o resultado
        if (alunoEncontrado == null) {
            // Caso NÃO encontre o aluno
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nenhum aluno encontrado com a matrícula: " + matricula,
                "Não Encontrado",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Caso ENCONTRE o aluno, formata e exibe os detalhes
            String detalhes = "--- Aluno Encontrado ---\n\n" +
                "Nome: " + alunoEncontrado.getNome() + "\n" +
                "Matrícula: " + alunoEncontrado.getMatricula() + "\n" +
                "Data Nasc.: " + alunoEncontrado.getDataNascimentoFormatadaCsv() + "\n" +
                "Idade: " + alunoEncontrado.getIdade() + "\n" +
                "CPF: " + alunoEncontrado.getCpf() + "\n" +
                "Telefone: " + alunoEncontrado.getTelefone();

            javax.swing.JOptionPane.showMessageDialog(this,
                detalhes,
                "Resultado da Pesquisa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        // 5. Limpa o campo de texto após a pesquisa
        matFieldData.setText("");
        SwingUtils.configurarPlaceholder(matFieldData, placeholder); // Recarrega o placeholder
    }//GEN-LAST:event_pesquisarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
         // 1. Pega a matrícula do campo de texto
        String matricula = matFieldData.getText();

        // 2. Validação simples
        if (matricula.isEmpty() || matricula.equals("Ex: 12345678")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite uma matrícula para excluir.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Apenas chama a exclusão.
        this.gerenciaAlunos.excluirAluno(matricula);

        // 4. Limpa o campo de texto
        matFieldData.setText("");
        
        // 5. Reaplica o placeholder
        SwingUtils.configurarPlaceholder(matFieldData, "Ex: 12345678"); 
    }//GEN-LAST:event_excluirActionPerformed

    public static void Table(listaAlunos gerenciaAlunos) {
        // ... (código de Look and Feel)

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrabConsData(gerenciaAlunos).setVisible(true));
    }

    /**
     * Preenche a JTable 'tabela' com os dados mais recentes 
     * da lista 'gerenciaAlunos'.
     */
    private void atualizarTabela() {
        // 1. Define os nomes das colunas
        String[] colunas = {"Nome", "Matricula", "Data de Nacimento", "CPF"};

        // 2. Cria um DefaultTableModel, iniciando com 0 linhas.
        DefaultTableModel model = new DefaultTableModel(colunas, 0);

        
        // --FILTRO/ORDENAÇÃO ---
        
        // 3. Pega a lista original
        List<Aluno> listaOriginal = this.gerenciaAlunos.listaAlunos;
        
        // 4. Cria uma copia mutavel para exibir (para não bagunçar a original)
        List<Aluno> alunosParaExibir = new ArrayList<>(listaOriginal);

        // 5. Verifica o que está selecionado no filtro
        String filtroSelecionado = listaFiltro.getSelectedValue();// 

        if (filtroSelecionado != null) {
            
            if (filtroSelecionado.equals("Mais Novo")) { 
            // "Mais novo" = maior data de nascimento (ordem decrescente)
                alunosParaExibir.sort(Comparator.comparing(
                aluno -> aluno.getDataNascimento(), // <-- MUDANÇA AQUI
                Comparator.nullsLast(Comparator.reverseOrder())
            ));
               
            } else if (filtroSelecionado.equals("Mais Velho")) { 
                // "Mais velho" = menor data de nascimento (ordem crescente)
                alunosParaExibir.sort(Comparator.comparing(
                aluno -> aluno.getDataNascimento(), // <-- MUDANÇA AQUI
                Comparator.nullsLast(Comparator.naturalOrder())
                ));
            }
        }
        // Se nada estiver selecionado, 'alunosParaExibir' 
        // permanece na ordem original (da lista principal)
        



        // 6. Itera sobre a lista ja filtrada
        for (Aluno aluno : alunosParaExibir) {
            
            // Cria um array de Objetos para a linha
            Object[] row = {
                aluno.getNome(),
                aluno.getMatricula(),
                aluno.getDataNascimentoFormatadaCsv(), //
                aluno.getCpf()
            };
            
            // Adiciona a linha ao modelo
            model.addRow(row);
        }

        // 7.define este modelo populado na sua JTable
        tabela.setModel(model);
    }
    
   
    public void atualizarTudo() {
        atualizarTabela();
        displayQnt.setText(this.gerenciaAlunos.getTamanho());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane displayQnt;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaFiltro;
    private javax.swing.JTextField matFieldData;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
